name: artemis
version: 7.13.1

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  build_config: ^1.1.1
  code_builder: ^4.4.0
  build: ^4.0.4
  collection: ^1.17.1
  dart_style: ^3.1.0
  equatable: ^2.0.5
  glob: ^2.1.1
  gql_code_builder: ^0.15.1
  gql_dedupe_link: ^4.0.0
  gql_exec: any
  gql_http_link: any
  gql_link: any
  gql: any
  http: ^1.1.0
  json_annotation: ^4.8.0
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.1

dev_dependencies:
  args: ^2.4.0
  build_runner: ^2.3.3
  build_test: ^3.5.10
  json_serializable: ^6.6.1
  test: ^1.22.2
  logging: ^1.1.1
  lints: ^6.1.0
